### ISSUE TITLE
docs: current state of translation

### ISSUE THREAD

**Issue by rojadesign** [vitejs/docs-de#222]
```[tasklist]
### Tasks
- [ ] docs/guide/migration.md
- [ ] docs/guide/api-environment.md
- [ ] docs/guide/api-environment-frameworks.md
- [ ] docs/guide/api-environment-instances.md
- [ ] docs/guide/api-environment-plugins.md
- [ ] docs/guide/api-environment-runtimes.md
```
